version: "3"

services:
    gnucash:
        build:
            context: gnucash
            args:
                - GROUP_GID=${GROUP_GID}
                - GROUP_NAME=${GROUP_NAME}
                - USER_UID=${USER_UID}
                - USER_NAME=${USER_NAME}
        image: gnucash3.3/python
        user: "${USER_UID}:${GROUP_GID}"
        volumes:
            - /samba/current-docs/GCF/gnucash_data:/docker/data
            - /samba/current-docs/GCF/gnucash_reports/pdf:/docker/pdf
            - /samba/current-docs/GCF/gnucash_reports/python:/docker/python
